# Generated by Django 5.2.6 on 2025-09-08 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deudor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('documento', models.CharField(max_length=50, unique=True, verbose_name='Documento de identidad')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Deudor',
                'verbose_name_plural': 'Deudores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=300, verbose_name='Concepto de la deuda')),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto original')),
                ('monto_pendiente', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto pendiente')),
                ('fecha_prestamo', models.DateField(verbose_name='Fecha del préstamo')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('tipo_pago', models.CharField(choices=[('UNICA', 'Pago Único'), ('DIFERIDA', 'Pago Diferido')], default='UNICA', max_length=10, verbose_name='Tipo de pago')),
                ('meses_diferido', models.PositiveIntegerField(blank=True, null=True, verbose_name='Meses diferidos')),
                ('tasa_interes', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tasa de interés (%)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('PARCIAL', 'Pago Parcial')], default='PENDIENTE', max_length=10)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='core.deudor')),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='PagoDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto del pago')),
                ('fecha_pago', models.DateField(verbose_name='Fecha del pago')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], max_length=50, verbose_name='Método de pago')),
                ('comprobante', models.CharField(blank=True, max_length=100, verbose_name='Número de comprobante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del pago')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.deuda')),
            ],
            options={
                'verbose_name': 'Pago de Deuda',
                'verbose_name_plural': 'Pagos de Deudas',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='CuotaDiferida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField(verbose_name='Número de cuota')),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto de la cuota')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('pagada', models.BooleanField(default=False, verbose_name='Pagada')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.deuda')),
            ],
            options={
                'verbose_name': 'Cuota Diferida',
                'verbose_name_plural': 'Cuotas Diferidas',
                'ordering': ['numero_cuota'],
                'unique_together': {('deuda', 'numero_cuota')},
            },
        ),
    ]
