# Generated by Django 5.2.6 on 2025-09-09 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acreedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del acreedor')),
                ('tipo', models.CharField(choices=[('BANCO', 'Banco'), ('PERSONA', 'Persona Natural'), ('EMPRESA', 'Empresa'), ('GOBIERNO', 'Entidad Gubernamental'), ('OTRO', 'Otro')], default='BANCO', max_length=10, verbose_name='Tipo de acreedor')),
                ('documento', models.CharField(blank=True, max_length=50, verbose_name='NIT/Documento')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('contacto_principal', models.CharField(blank=True, max_length=100, verbose_name='Contacto principal')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Acreedor',
                'verbose_name_plural': 'Acreedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MiDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, verbose_name='Número de cuenta/contrato')),
                ('tipo_deuda', models.CharField(choices=[('PRESTAMO', 'Préstamo Personal'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('HIPOTECA', 'Hipoteca'), ('VEHICULO', 'Crédito Vehículo'), ('COMERCIAL', 'Crédito Comercial'), ('LIBRANZA', 'Crédito Libranza'), ('PERSONAL', 'Deuda Personal'), ('SERVICIO', 'Servicio (Agua, Luz, etc.)'), ('IMPUESTO', 'Impuesto'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de deuda')),
                ('concepto', models.CharField(max_length=300, verbose_name='Concepto/Descripción')),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto original')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo pendiente')),
                ('tasa_interes', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tasa de interés anual (%)')),
                ('fecha_contrato', models.DateField(verbose_name='Fecha del contrato')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('cuota_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cuota mensual')),
                ('plazo_meses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Plazo en meses')),
                ('prioridad', models.CharField(choices=[('ALTA', 'Prioridad Alta'), ('MEDIA', 'Prioridad Media'), ('BAJA', 'Prioridad Baja')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('PARCIAL', 'Pago Parcial'), ('REFINANCIADA', 'Refinanciada'), ('CONDONADA', 'Condonada')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('acreedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_deudas', to='core.acreedor')),
            ],
            options={
                'verbose_name': 'Mi Deuda',
                'verbose_name_plural': 'Mis Deudas',
                'ordering': ['-fecha_contrato'],
            },
        ),
        migrations.CreateModel(
            name='MiPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto del pago')),
                ('monto_capital', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto aplicado a capital')),
                ('monto_interes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto aplicado a intereses')),
                ('fecha_pago', models.DateField(verbose_name='Fecha del pago')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('DEBITO_AUTOMATICO', 'Débito Automático'), ('CHEQUE', 'Cheque'), ('PSE', 'PSE'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('OTRO', 'Otro')], max_length=50, verbose_name='Método de pago')),
                ('numero_transaccion', models.CharField(blank=True, max_length=100, verbose_name='Número de transacción')),
                ('comprobante', models.CharField(blank=True, max_length=100, verbose_name='Número de comprobante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('mi_deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_pagos', to='core.mideuda')),
            ],
            options={
                'verbose_name': 'Mi Pago',
                'verbose_name_plural': 'Mis Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='RecordatorioDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recordatorio', models.DateField(verbose_name='Fecha del recordatorio')),
                ('dias_anticipacion', models.PositiveIntegerField(default=5, verbose_name='Días de anticipación')),
                ('mensaje', models.TextField(verbose_name='Mensaje del recordatorio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('mi_deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='core.mideuda')),
            ],
            options={
                'verbose_name': 'Recordatorio de Deuda',
                'verbose_name_plural': 'Recordatorios de Deudas',
                'ordering': ['fecha_recordatorio'],
            },
        ),
    ]
