# Generated by Django 5.2.6 on 2025-09-16 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_acreedor_mideuda_mipago_recordatoriodeuda'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la meta')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('AHORRO', 'Ahorro'), ('INVERSION', 'Inversión'), ('DEUDA', 'Pago de Deuda'), ('COMPRA', 'Compra Específica'), ('EMERGENCIA', 'Fondo de Emergencia'), ('OTRO', 'Otro')], max_length=12, verbose_name='Tipo de meta')),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto objetivo')),
                ('monto_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto actual')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_objetivo', models.DateField(verbose_name='Fecha objetivo')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('COMPLETADA', 'Completada'), ('PAUSADA', 'Pausada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=12, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta Financiera',
                'verbose_name_plural': 'Metas Financieras',
                'ordering': ['-fecha_objetivo'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('naturaleza', models.CharField(choices=[('FIJO', 'Fijo'), ('VARIABLE', 'Variable')], max_length=10, verbose_name='Naturaleza')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría Financiera',
                'verbose_name_plural': 'Categorías Financieras',
                'ordering': ['tipo', 'naturaleza', 'nombre'],
                'unique_together': {('nombre', 'tipo', 'naturaleza')},
            },
        ),
        migrations.CreateModel(
            name='SubcategoriaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la subcategoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='core.categoriafinanciera')),
            ],
            options={
                'verbose_name': 'Subcategoría Financiera',
                'verbose_name_plural': 'Subcategorías Financieras',
                'ordering': ['categoria', 'nombre'],
                'unique_together': {('categoria', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='PresupuestoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField(verbose_name='Año')),
                ('mes', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Mes')),
                ('monto_presupuestado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto presupuestado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='core.categoriafinanciera')),
            ],
            options={
                'verbose_name': 'Presupuesto por Categoría',
                'verbose_name_plural': 'Presupuestos por Categoría',
                'ordering': ['-año', '-mes', 'categoria__nombre'],
                'unique_together': {('categoria', 'año', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('fecha', models.DateField(verbose_name='Fecha del movimiento')),
                ('es_recurrente', models.BooleanField(default=False, verbose_name='Es recurrente')),
                ('frecuencia', models.CharField(blank=True, choices=[('UNICO', 'Único'), ('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=12, verbose_name='Frecuencia')),
                ('fecha_fin_recurrencia', models.DateField(blank=True, null=True, verbose_name='Fecha fin recurrencia')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('CHEQUE', 'Cheque'), ('PSE', 'PSE'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20, verbose_name='Método de pago')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia/Número de transacción')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('comprobante', models.CharField(blank=True, max_length=100, verbose_name='Número de comprobante')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.categoriafinanciera')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.subcategoriafinanciera')),
            ],
            options={
                'verbose_name': 'Movimiento Financiero',
                'verbose_name_plural': 'Movimientos Financieros',
                'ordering': ['-fecha', '-fecha_creacion'],
                'indexes': [models.Index(fields=['fecha'], name='core_movimi_fecha_b015fa_idx'), models.Index(fields=['tipo'], name='core_movimi_tipo_1ce419_idx'), models.Index(fields=['categoria'], name='core_movimi_categor_471ecd_idx')],
            },
        ),
    ]
